#Config MAp to store ngninx.conf 
# kubectl apply -f nginx-config.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-waf
data:
  nginx.conf: |-
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    load_module modules/ngx_http_modsecurity_module.so;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        sendfile        on;
        keepalive_timeout  65;

        upstream webapp {
            server 127.0.0.1:80;
        }

        server {
            listen 81;
            
            modsecurity on;
            modsecurity_rules_file /etc/nginx/modsec/main.conf;

            location / {
                proxy_pass         http://webapp;
                proxy_redirect     off;
            }
        }
    }
